// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import BookRentalReturnController from "./book_rental_return_controller.js"
application.register("book-rental-return", BookRentalReturnController)

import ReturnsFormController from "./returns_form_controller.js"
application.register("returns-form", ReturnsFormController)
